# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1Pr7DV6NT7zzaw-0frYIDAdCln9iFtg
"""

"""
ETL Pipeline - The Tea Clone Performance Index
"""

import pandas as pd
import numpy as np
import os

RAW_AUCTION_PATH = "data/ktda_auction_files_2022-2025.csv"
CLONE_MAPPING_PATH = "data/clone_mapping.csv"
OUTPUT_DIR = "outputs/tables"
PROCESSED_LOT_PATH = "data/processed_lot_level.csv"
PROCESSED_QUARTERLY_PATH = "data/processed_quarterly_clone_panel.csv"

os.makedirs(OUTPUT_DIR, exist_ok=True)


def load_raw_data():
    """Load raw auction lot data and clone mapping reference table."""
    auctions = pd.read_csv(RAW_AUCTION_PATH)
    mapping = pd.read_csv(CLONE_MAPPING_PATH)
    return auctions, mapping
def clean_auction_data(df):
    """Standardise types, parse dates, remove duplicates, check missing values."""
    n_before = len(df)

    # Standardise column names
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]

    # Parse dates - file uses M/D/YYYY format
    df["sale_date"] = pd.to_datetime(df["sale_date"], format="%m/%d/%Y", errors="coerce")

    # Drop rows with unparseable dates
    df = df.dropna(subset=["sale_date"])

    # Standardise categorical text fields
    for col in ["factory", "grade", "clone_type", "lot_number"]:
        df[col] = df[col].astype(str).str.strip()

    # Remove exact duplicate lot records
    n_dupes = df.duplicated(subset=["lot_number", "sale_date"]).sum()
    df = df.drop_duplicates(subset=["lot_number", "sale_date"])

    # Numeric sanity checks - clip impossible negative values
    numeric_cols = ["auction_price_usd", "exchange_rate", "rainfall_mm",
                     "temperature_c", "made_tea_kg", "bp1_share"]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df = df.dropna(subset=numeric_cols)
    df = df[(df["auction_price_usd"] > 0) & (df["made_tea_kg"] > 0)]

    # Outlier treatment on auction price using IQR capping (winsorisation)
    q1, q3 = df["auction_price_usd"].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    n_outliers = ((df["auction_price_usd"] < lower) | (df["auction_price_usd"] > upper)).sum()
    df["auction_price_usd"] = df["auction_price_usd"].clip(lower, upper)

    n_after = len(df)
    report = {
        "rows_before": n_before,
        "rows_after_dedup_and_clean": n_after,
        "duplicates_removed": int(n_dupes),
        "price_outliers_capped": int(n_outliers),
    }
    return df, report


def validate_clone_mapping(auctions, mapping):
    # Derive lot prefix
    auctions = auctions.copy()
    auctions["lot_prefix"] = auctions["lot_number"].str.rsplit("-", n=1).str[0]

    merged = auctions.merge(
        mapping[["factory", "lot_prefix", "clone_type"]],
        on=["factory", "lot_prefix"],
        how="left",
        suffixes=("", "_ref"),
    )

    mismatches = merged[merged["clone_type"] != merged["clone_type_ref"]]
    unmatched = merged["clone_type_ref"].isna().sum()

    validation_report = {
        "total_lots": len(merged),
        "lots_matched_to_reference": int((~merged["clone_type_ref"].isna()).sum()),
        "lots_unmatched": int(unmatched),
        "clone_label_mismatches": int(len(mismatches)),
    }

    # Use the validated clone_type
    merged["clone_type_final"] = merged["clone_type_ref"].fillna(merged["clone_type"])
    merged["clone_type"] = merged["clone_type_final"]
    merged = merged.drop(columns=["clone_type_ref", "clone_type_final", "lot_prefix"])

    return merged, validation_report


def engineer_lot_features(df):
    """Add calendar and economic engineered features at lot level."""
    df = df.copy()
    df["year"] = df["sale_date"].dt.year
    df["quarter"] = df["sale_date"].dt.quarter
    df["month"] = df["sale_date"].dt.month
    df["year_quarter"] = df["year"].astype(str) + "Q" + df["quarter"].astype(str)

    # Seasonal indicator (Kenyan tea seasons: peak rain season ~ Mar-May & Oct-Dec)
    df["season"] = np.where(df["month"].isin([3, 4, 5, 10, 11, 12]), "high_rain", "dry")

    # Price converted to KES using the exchange rate of that auction date
    df["auction_price_kes"] = df["auction_price_usd"] * df["exchange_rate"]

    # Revenue proxy for the lot (price per kg * kg made)
    df["lot_revenue_usd"] = df["auction_price_usd"] * df["made_tea_kg"]

    return df


def build_quarterly_clone_panel(df):
    """
    Aggregate lot-level data into a quarterly clone-level panel - the
    primary modelling unit for the time-series forecasting task.
    """
    agg = df.groupby(["clone_type", "year", "quarter", "year_quarter"]).agg(
        avg_price_usd=("auction_price_usd", "mean"),
        median_price_usd=("auction_price_usd", "median"),
        price_std=("auction_price_usd", "std"),
        total_made_tea_kg=("made_tea_kg", "sum"),
        avg_bp1_share=("bp1_share", "mean"),
        avg_rainfall_mm=("rainfall_mm", "mean"),
        avg_temperature_c=("temperature_c", "mean"),
        avg_exchange_rate=("exchange_rate", "mean"),
        n_lots=("lot_number", "count"),
        total_revenue_usd=("lot_revenue_usd", "sum"),
    ).reset_index()

    agg["price_std"] = agg["price_std"].fillna(0)
    agg["coefficient_of_variation"] = agg["price_std"] / agg["avg_price_usd"]

    # Sort for time-series feature creation
    agg = agg.sort_values(["clone_type", "year", "quarter"]).reset_index(drop=True)

    # Lagged price features (t-1, t-2) and rolling mean, per clone
    agg["price_lag1"] = agg.groupby("clone_type")["avg_price_usd"].shift(1)
    agg["price_lag2"] = agg.groupby("clone_type")["avg_price_usd"].shift(2)
    agg["price_rolling_mean3"] = (
        agg.groupby("clone_type")["avg_price_usd"]
        .transform(lambda s: s.shift(1).rolling(window=3, min_periods=1).mean())
    )
    agg["price_pct_change"] = agg.groupby("clone_type")["avg_price_usd"].pct_change()

    # Seasonal one-hot for quarter
    for q in [1, 2, 3, 4]:
        agg[f"is_q{q}"] = (agg["quarter"] == q).astype(int)

    # Drop rows without lag history (first 2 quarters per clone) for supervised modelling
    model_ready = agg.dropna(subset=["price_lag1", "price_lag2"]).reset_index(drop=True)

    return agg, model_ready


def run_pipeline():
    auctions, mapping = load_raw_data()
    auctions_clean, clean_report = clean_auction_data(auctions)
    auctions_validated, validation_report = validate_clone_mapping(auctions_clean, mapping)
    auctions_featured = engineer_lot_features(auctions_validated)

    quarterly_full, quarterly_model_ready = build_quarterly_clone_panel(auctions_featured)

    auctions_featured.to_csv(PROCESSED_LOT_PATH, index=False)
    quarterly_full.to_csv(PROCESSED_QUARTERLY_PATH, index=False)
    quarterly_model_ready.to_csv("data/processed_quarterly_model_ready.csv", index=False)

    print("=== Data Cleaning Report ===")
    for k, v in clean_report.items():
        print(f"{k}: {v}")
    print("\n=== Clone Mapping Validation Report ===")
    for k, v in validation_report.items():
        print(f"{k}: {v}")
    print(f"\nLot-level processed rows: {len(auctions_featured)}")
    print(f"Quarterly clone panel rows: {len(quarterly_full)}")
    print(f"Model-ready quarterly rows: {len(quarterly_model_ready)}")

    return auctions_featured, quarterly_full, quarterly_model_ready, clean_report, validation_report


if __name__ == "__main__":
    run_pipeline()

"""
Exploratory Data Analysis
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set_theme(style="whitegrid", palette="deep")
FIG_DIR = "outputs/figures"
TAB_DIR = "outputs/tables"
os.makedirs(FIG_DIR, exist_ok=True)
os.makedirs(TAB_DIR, exist_ok=True)

lot = pd.read_csv("data/processed_lot_level.csv", parse_dates=["sale_date"])
qtr = pd.read_csv("data/processed_quarterly_clone_panel.csv")

# ---------------------------------------------------------------
# 1. Descriptive statistics tables
# ---------------------------------------------------------------
desc = lot[["auction_price_usd", "rainfall_mm", "temperature_c",
            "made_tea_kg", "bp1_share", "exchange_rate"]].describe().T
desc.to_csv(f"{TAB_DIR}/lot_level_descriptive_stats.csv")

clone_summary = lot.groupby("clone_type")["auction_price_usd"].agg(
    ["mean", "std", "min", "max", "count"]
).reset_index()
clone_summary.to_csv(f"{TAB_DIR}/clone_price_summary.csv", index=False)

grade_summary = lot.groupby("grade")["auction_price_usd"].agg(
    ["mean", "std", "count"]
).reset_index()
grade_summary.to_csv(f"{TAB_DIR}/grade_price_summary.csv", index=False)

# ---------------------------------------------------------------
# 2. Price distribution by clone (boxplot)
# ---------------------------------------------------------------
plt.figure(figsize=(9, 5.5))
order = lot.groupby("clone_type")["auction_price_usd"].median().sort_values(ascending=False).index
sns.boxplot(data=lot, x="clone_type", y="auction_price_usd", order=order)
plt.title("Figure 4.1: Auction Price Distribution by Tea Clone (2022-2025)")
plt.xlabel("Clone Type")
plt.ylabel("Auction Price (USD/kg)")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_1_price_by_clone_boxplot.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# 3. Price distribution by grade
# ---------------------------------------------------------------
plt.figure(figsize=(8, 5))
order_g = lot.groupby("grade")["auction_price_usd"].median().sort_values(ascending=False).index
sns.boxplot(data=lot, x="grade", y="auction_price_usd", order=order_g)
plt.title("Figure 4.2: Auction Price Distribution by Tea Grade")
plt.xlabel("Grade")
plt.ylabel("Auction Price (USD/kg)")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_2_price_by_grade_boxplot.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# 4. Time series of quarterly average price per clone
# ---------------------------------------------------------------
plt.figure(figsize=(11, 6))
for clone in qtr["clone_type"].unique():
    sub = qtr[qtr["clone_type"] == clone].sort_values(["year", "quarter"])
    plt.plot(sub["year_quarter"], sub["avg_price_usd"], marker="o", label=clone)
plt.xticks(rotation=60)
plt.title("Figure 4.3: Quarterly Average Auction Price by Clone (2022-2025)")
plt.xlabel("Year-Quarter")
plt.ylabel("Average Auction Price (USD/kg)")
plt.legend(title="Clone")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_3_quarterly_price_trend_by_clone.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# 5. Correlation heatmap (lot-level numeric features)
# ---------------------------------------------------------------
num_cols = ["auction_price_usd", "exchange_rate", "rainfall_mm",
            "temperature_c", "made_tea_kg", "bp1_share"]
corr = lot[num_cols].corr()
corr.to_csv(f"{TAB_DIR}/correlation_matrix.csv")

plt.figure(figsize=(8, 6.5))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", vmin=-1, vmax=1)
plt.title("Figure 4.4: Correlation Heatmap of Lot-Level Numeric Variables")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_4_correlation_heatmap.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# 6. Seasonal price pattern (monthly average across years)
# ---------------------------------------------------------------
lot["month"] = pd.to_datetime(lot["sale_date"]).dt.month
monthly = lot.groupby("month")["auction_price_usd"].mean().reset_index()
plt.figure(figsize=(8, 5))
sns.barplot(data=monthly, x="month", y="auction_price_usd", color="seagreen")
plt.title("Figure 4.5: Average Auction Price by Calendar Month (2022-2025)")
plt.xlabel("Month")
plt.ylabel("Average Auction Price (USD/kg)")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_5_seasonal_price_pattern.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# 7. BP1 share vs price scatter
# ---------------------------------------------------------------
plt.figure(figsize=(7.5, 5.5))
sns.scatterplot(data=lot.sample(min(3000, len(lot)), random_state=42),
                 x="bp1_share", y="auction_price_usd", hue="clone_type", alpha=0.5, s=18)
plt.title("Figure 4.6: BP1 Grade Share vs Auction Price")
plt.xlabel("BP1 Share")
plt.ylabel("Auction Price (USD/kg)")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_6_bp1share_vs_price.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# 8. Class / clone distribution (lot counts)
# ---------------------------------------------------------------
plt.figure(figsize=(8, 5))
sns.countplot(data=lot, x="clone_type",
               order=lot["clone_type"].value_counts().index, color="steelblue")
plt.title("Figure 4.7: Number of Auction Lots per Clone Type (2022-2025)")
plt.xlabel("Clone Type")
plt.ylabel("Number of Lots")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_7_lot_count_by_clone.png", dpi=150)
plt.close()

print("EDA complete. Figures saved to", FIG_DIR)
print("Tables saved to", TAB_DIR)
print("\nClone summary:\n", clone_summary)
print("\nCorrelation matrix:\n", corr)

"""
Modelling Pipeline
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
from sklearn.ensemble import RandomForestRegressor, HistGradientBoostingRegressor
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

sns.set_theme(style="whitegrid")
FIG_DIR = "outputs/figures"
TAB_DIR = "outputs/tables"
MODEL_DIR = "outputs/models"
for d in [FIG_DIR, TAB_DIR, MODEL_DIR]:
    os.makedirs(d, exist_ok=True)

SEED = 42
np.random.seed(SEED)

df = pd.read_csv("data/processed_quarterly_model_ready.csv")
df = df.sort_values(["clone_type", "year", "quarter"]).reset_index(drop=True)

FEATURES = [
    "price_lag1", "price_lag2", "price_rolling_mean3",
    "avg_bp1_share", "avg_rainfall_mm", "avg_temperature_c",
    "avg_exchange_rate", "is_q1", "is_q2", "is_q3", "is_q4",
]
TARGET = "avg_price_usd"

# One-hot encode clone identity so a single global model can learn
# clone-specific effects.
clone_dummies = pd.get_dummies(df["clone_type"], prefix="clone")
X_full = pd.concat([df[FEATURES], clone_dummies], axis=1)
y_full = df[TARGET]

# ---------------------------------------------------------------
# Time-based split: train on 2022Q3-2024Q4, test on 2025 quarters
# (per-clone, preserving chronology)
# ---------------------------------------------------------------
df["period_index"] = df["year"] * 4 + df["quarter"]
split_threshold = 2025 * 4 + 1  # test = 2025 Q1 onward

train_mask = df["period_index"] < split_threshold
test_mask = ~train_mask

X_train, X_test = X_full[train_mask], X_full[test_mask]
y_train, y_test = y_full[train_mask], y_full[test_mask]

print(f"Train rows: {len(X_train)}, Test rows: {len(X_test)}")
print("Test period(s):", sorted(df.loc[test_mask, "year_quarter"].unique()))


# ---------------------------------------------------------------
# Baseline 1: Naive persistence (predict price_lag1)
# ---------------------------------------------------------------
pred_naive = X_test["price_lag1"].values

# ---------------------------------------------------------------
# Baseline 2: Seasonal naive (same quarter, previous year average per clone)
# ---------------------------------------------------------------
seasonal_lookup = (
    df[df["year"] == 2024]
    .groupby(["clone_type", "quarter"])["avg_price_usd"].mean()
    .to_dict()
)
pred_seasonal = df.loc[test_mask].apply(
    lambda r: seasonal_lookup.get((r["clone_type"], r["quarter"]), r["price_lag1"]), axis=1
).values


# ---------------------------------------------------------------
# Model 3: Random Forest Regressor (with GridSearch tuning)
# ---------------------------------------------------------------
rf_param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [3, 5, 8, None],
    "min_samples_leaf": [1, 2, 4],
}
tscv = TimeSeriesSplit(n_splits=4)
rf_search = GridSearchCV(
    RandomForestRegressor(random_state=SEED),
    rf_param_grid, cv=tscv, scoring="neg_mean_absolute_error", n_jobs=-1
)
rf_search.fit(X_train, y_train)
rf_best = rf_search.best_estimator_
pred_rf = rf_best.predict(X_test)

# ---------------------------------------------------------------
# Model 4: HistGradientBoostingRegressor (XGBoost-equivalent, tuned)
# ---------------------------------------------------------------
gbm_param_grid = {
    "max_iter": [100, 200, 300],
    "max_depth": [2, 3, 5],
    "learning_rate": [0.01, 0.05, 0.1],
    "l2_regularization": [0.0, 0.1, 1.0],
}
gbm_search = GridSearchCV(
    HistGradientBoostingRegressor(random_state=SEED),
    gbm_param_grid, cv=tscv, scoring="neg_mean_absolute_error", n_jobs=-1
)
gbm_search.fit(X_train, y_train)
gbm_best = gbm_search.best_estimator_
pred_gbm = gbm_best.predict(X_test)


# ---------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------
def evaluate(name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    return {"model": name, "MAE": round(mae, 4), "RMSE": round(rmse, 4), "R2": round(r2, 4)}


results = [
    evaluate("Naive Persistence (t-1)", y_test, pred_naive),
    evaluate("Seasonal Naive (prev. year same quarter)", y_test, pred_seasonal),
    evaluate("Random Forest Regressor (tuned)", y_test, pred_rf),
    evaluate("HistGradientBoosting (XGBoost-equivalent, tuned)", y_test, pred_gbm),
]
results_df = pd.DataFrame(results)
results_df.to_csv(f"{TAB_DIR}/model_comparison_results.csv", index=False)
print("\n=== Model Comparison ===")
print(results_df)

# Save best hyperparameters
hyperparams = {
    "RandomForest_best_params": rf_search.best_params_,
    "RandomForest_best_cv_MAE": -rf_search.best_score_,
    "HistGBM_best_params": gbm_search.best_params_,
    "HistGBM_best_cv_MAE": -gbm_search.best_score_,
}
with open(f"{TAB_DIR}/best_hyperparameters.json", "w") as f:
    json.dump(hyperparams, f, indent=2, default=str)
print("\nBest hyperparameters:\n", json.dumps(hyperparams, indent=2, default=str))


# ---------------------------------------------------------------
# Determine champion model
# ---------------------------------------------------------------
champion_row = results_df.loc[results_df["MAE"].idxmin()]
champion_name = champion_row["model"]
champion_preds = {
    "Naive Persistence (t-1)": pred_naive,
    "Seasonal Naive (prev. year same quarter)": pred_seasonal,
    "Random Forest Regressor (tuned)": pred_rf,
    "HistGradientBoosting (XGBoost-equivalent, tuned)": pred_gbm,
}[champion_name]
print(f"\nChampion model: {champion_name}")


# ---------------------------------------------------------------
# Figure 4.8: Predicted vs Actual (champion model)
# ---------------------------------------------------------------
plt.figure(figsize=(7, 6))
plt.scatter(y_test, champion_preds, alpha=0.7, edgecolor="k")
lims = [min(y_test.min(), champion_preds.min()), max(y_test.max(), champion_preds.max())]
plt.plot(lims, lims, "r--", label="Perfect prediction")
plt.xlabel("Actual Avg. Price (USD/kg)")
plt.ylabel("Predicted Avg. Price (USD/kg)")
plt.title(f"Figure 4.8: Predicted vs Actual Quarterly Price\n({champion_name})")
plt.legend()
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_8_predicted_vs_actual.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# Figure 4.9: Residual distribution
# ---------------------------------------------------------------
residuals = y_test.values - champion_preds
plt.figure(figsize=(7.5, 5.4))
sns.histplot(residuals, kde=True, color="darkorange")
plt.axvline(0, color="k", linestyle="--")
plt.title("Figure 4.9: Residual Distribution\n(Champion Model: HistGradientBoosting)", fontsize=13)
plt.xlabel("Residual (Actual - Predicted) USD/kg")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_9_residual_distribution.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# Figure 4.10: Feature importance (Random Forest)
# ---------------------------------------------------------------
importances = pd.Series(rf_best.feature_importances_, index=X_full.columns).sort_values(ascending=False)
importances.to_csv(f"{TAB_DIR}/rf_feature_importances.csv")
plt.figure(figsize=(8, 6))
importances.head(10).plot(kind="barh", color="teal")
plt.gca().invert_yaxis()
plt.title("Figure 4.10: Top 10 Feature Importances (Random Forest)")
plt.xlabel("Importance")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_10_rf_feature_importance.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# Figure 4.11: Learning curve (training set size vs MAE) for champion-class model
# ---------------------------------------------------------------
from sklearn.model_selection import learning_curve
lc_model = rf_best if "Random Forest" in champion_name else gbm_best
train_sizes, train_scores, val_scores = learning_curve(
    lc_model, X_train, y_train, cv=tscv,
    scoring="neg_mean_absolute_error",
    train_sizes=np.linspace(0.3, 1.0, 5)
)
plt.figure(figsize=(7, 5))
plt.plot(train_sizes, -train_scores.mean(axis=1), marker="o", label="Training MAE")
plt.plot(train_sizes, -val_scores.mean(axis=1), marker="o", label="Validation MAE")
plt.xlabel("Training Set Size")
plt.ylabel("MAE (USD/kg)")
plt.title(f"Figure 4.11: Learning Curve ({champion_name.split('(')[0].strip()})")
plt.legend()
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_11_learning_curve.png", dpi=150)
plt.close()


# ---------------------------------------------------------------
# Predictions table for 2025 test quarters (per clone)
# ---------------------------------------------------------------
pred_table = df.loc[test_mask, ["clone_type", "year_quarter", "avg_price_usd"]].copy()
pred_table["predicted_price_naive"] = pred_naive
pred_table["predicted_price_seasonal"] = pred_seasonal
pred_table["predicted_price_rf"] = pred_rf
pred_table["predicted_price_gbm"] = pred_gbm
pred_table["champion_prediction"] = champion_preds
pred_table.to_csv(f"{TAB_DIR}/quarterly_predictions_2025.csv", index=False)
print("\nPredictions table:\n", pred_table)


# Save champion model
import joblib
joblib.dump(rf_best, f"{MODEL_DIR}/random_forest_model.joblib")
joblib.dump(gbm_best, f"{MODEL_DIR}/hist_gbm_model.joblib")
with open(f"{MODEL_DIR}/champion_model.txt", "w") as f:
    f.write(champion_name)

print("\nModelling complete. Outputs saved to outputs/")

"""
Prescriptive Analytics Pipeline
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set_theme(style="whitegrid")
FIG_DIR = "outputs/figures"
TAB_DIR = "outputs/tables"

# ---------------------------------------------------------------
# Assumptions (documented for transparency / reproducibility)
# ---------------------------------------------------------------
AVG_YIELD_KG_PER_HA_PER_QUARTER = 1500   # green leaf -> made tea kg, smallholder average
PRODUCTION_COST_USD_PER_KG = 1.35        # average cost of production per kg made tea
KTDA_BONUS_SHARE = 0.45                  # share of net surplus distributed as bonus

quarterly = pd.read_csv("data/processed_quarterly_clone_panel.csv")
predictions = pd.read_csv(f"{TAB_DIR}/quarterly_predictions_2025.csv")

# ---------------------------------------------------------------
# 1. Historical stability metrics per clone (full history)
# ---------------------------------------------------------------
stability = quarterly.groupby("clone_type").agg(
    historical_avg_price=("avg_price_usd", "mean"),
    historical_price_std=("avg_price_usd", "std"),
).reset_index()
stability["coefficient_of_variation"] = (
    stability["historical_price_std"] / stability["historical_avg_price"]
)

# ---------------------------------------------------------------
# 2. Forecasted 2025 economics per clone (using champion predictions)
# ---------------------------------------------------------------
forecast = predictions.groupby("clone_type").agg(
    forecast_avg_price_2025=("champion_prediction", "mean")
).reset_index()

econ = forecast.merge(stability, on="clone_type")

# Annual revenue per hectare = forecast price * yield * 4 quarters
econ["annual_revenue_usd_per_ha"] = econ["forecast_avg_price_2025"] * AVG_YIELD_KG_PER_HA_PER_QUARTER * 4
econ["annual_cost_usd_per_ha"] = PRODUCTION_COST_USD_PER_KG * AVG_YIELD_KG_PER_HA_PER_QUARTER * 4
econ["annual_net_surplus_usd_per_ha"] = econ["annual_revenue_usd_per_ha"] - econ["annual_cost_usd_per_ha"]
econ["expected_annual_bonus_usd_per_ha"] = econ["annual_net_surplus_usd_per_ha"] * KTDA_BONUS_SHARE
econ["roi_pct"] = (econ["annual_net_surplus_usd_per_ha"] / econ["annual_cost_usd_per_ha"]) * 100

# ---------------------------------------------------------------
# 3. Composite ranking score
#    Normalised expected return (60%) minus normalised volatility (40%)
# ---------------------------------------------------------------
def normalise(s):
    return (s - s.min()) / (s.max() - s.min())

econ["norm_return"] = normalise(econ["annual_net_surplus_usd_per_ha"])
econ["norm_volatility"] = normalise(econ["coefficient_of_variation"])
econ["composite_score"] = 0.6 * econ["norm_return"] + 0.4 * (1 - econ["norm_volatility"])

econ = econ.sort_values("composite_score", ascending=False).reset_index(drop=True)
econ["rank"] = range(1, len(econ) + 1)

econ.to_csv(f"{TAB_DIR}/clone_economic_ranking.csv", index=False)
print("=== Clone Economic Ranking (2025 forecast) ===")
print(econ[["rank", "clone_type", "forecast_avg_price_2025",
             "coefficient_of_variation", "expected_annual_bonus_usd_per_ha",
             "roi_pct", "composite_score"]])

# ---------------------------------------------------------------
# Figure: Clone ranking bar chart (composite score)
# ---------------------------------------------------------------
plt.figure(figsize=(8, 5))
sns.barplot(data=econ, x="clone_type", y="composite_score",
            order=econ["clone_type"], color="darkgreen")
plt.title("Figure 4.12: Clone Performance Index - Composite Ranking Score (2025 Forecast)")
plt.ylabel("Composite Score (0-1, higher = better)")
plt.xlabel("Clone Type")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_12_composite_ranking.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# Figure: Expected annual bonus per hectare by clone
# ---------------------------------------------------------------
plt.figure(figsize=(8, 5))
sns.barplot(data=econ, x="clone_type", y="expected_annual_bonus_usd_per_ha",
            order=econ["clone_type"], color="goldenrod")
plt.title("Figure 4.13: Expected Annual Bonus per Hectare by Clone (USD, 2025 Forecast)")
plt.ylabel("Expected Annual Bonus (USD/ha)")
plt.xlabel("Clone Type")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_13_expected_bonus.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# Figure: Risk-Return scatter (volatility vs forecast price)
# ---------------------------------------------------------------
plt.figure(figsize=(7.5, 5.5))
for _, row in econ.iterrows():
    plt.scatter(row["coefficient_of_variation"], row["forecast_avg_price_2025"], s=100)
    plt.annotate(row["clone_type"], (row["coefficient_of_variation"], row["forecast_avg_price_2025"]),
                 xytext=(5, 5), textcoords="offset points")
plt.xlabel("Price Volatility (Coefficient of Variation)")
plt.ylabel("Forecast Avg. Price 2025 (USD/kg)")
plt.title("Figure 4.14: Risk-Return Profile of Tea Clones")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_14_risk_return_scatter.png", dpi=150)
plt.close()

# ---------------------------------------------------------------
# Scenario analysis: what-if exchange rate shock (+/- 5%)
# ---------------------------------------------------------------
scenarios = []
for shock_name, shock_factor in [("Baseline", 1.0), ("KES Depreciation +5%", 1.05), ("KES Appreciation -5%", 0.95)]:
    temp = econ.copy()
    temp["scenario"] = shock_name
    temp["adj_annual_bonus_usd_per_ha"] = temp["expected_annual_bonus_usd_per_ha"] * shock_factor
    scenarios.append(temp[["clone_type", "scenario", "adj_annual_bonus_usd_per_ha"]])
scenario_df = pd.concat(scenarios)
scenario_df.to_csv(f"{TAB_DIR}/scenario_analysis_exchange_rate.csv", index=False)

plt.figure(figsize=(9, 5.5))
sns.barplot(data=scenario_df, x="clone_type", y="adj_annual_bonus_usd_per_ha", hue="scenario")
plt.title("Figure 4.15: Scenario Analysis - Exchange Rate Sensitivity of Expected Bonus")
plt.ylabel("Expected Annual Bonus (USD/ha)")
plt.xlabel("Clone Type")
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/fig_4_15_scenario_analysis.png", dpi=150)
plt.close()

print("\nPrescriptive analytics complete. Outputs saved to outputs/")